spring.application.name=ravenshop
server.port=8081

ravendb.url=http://127.0.0.1:8085
ravendb.database=RavenShop

ravenshop.seed.enabled=false

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
